logging.file.name=logs/app-dev.log
logging.access.file.name=logs/access-dev.log

spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

jwt.key=11dcf9ab53dd8f8acba05bee6c22be72990ef39b59e12736f13c8d6ea0f2b428
