logging.file.name=logs/app-dev.log
logging.access.file.name=logs/access-dev.log

spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
